<?php

namespace Database\Seeders;

use App\Models\Alert;
use Faker\Generator;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AlertSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = app(Generator::class);

        for ($i = 1; $i < 31; $i++) {
            Alert::create([
                'title'         => 'Alert '.$i,
                'description'   => 'This description is autogenerated for Alert '.$i,
                'priority'      => $faker->randomElement(['Low', 'Medium', 'High']),
                'status'        => true
            ]);
        }
    }
}
